[package]
name = "Left_to_right_modular_exponentiation"
version = "0.1.0"
authors = ["Leonhard Bosch <lbosch@stud.hs-heilbronn.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
